### ISSUE TITLE
About cover screen menu display

### ISSUE THREAD

**Issue by baykaraktersizz** [SamSprung/SamSprung-TooUI#107]
I have just upgraded the Samsprung app. After upgrading ı've realized that cover screen menu display changed. We need to scroll down to find the apps. I would highly recommend you to apply the previous one since it used to look better.
![WhatsApp Image 2022-03-17 at 7 14 59 PM](https://user-images.githubusercontent.com/101820147/158847404-dd8b521a-a0ff-426a-8f9c-fb793c5de9d1.jpeg)
![WhatsApp Image 2022-03-17 at 7 15 32 PM](https://user-images.githubusercontent.com/101820147/158847416-89badb0d-4282-4d6f-ab50-9e6367238b49.jpeg)

**Comment by AbandonedCart** [comment]
I highly recommend staying updated.
