### ISSUE TITLE
Please fix the minor system issues. People will really love this tool including me! I been waiting for this Idk y it does this it literally stops functioning after few hours, the swipe back to previous screen ,swipe from any side of the screen,also swipe up from bottom middle screen to return to homescreen just stops To turn off my phone I had to pull down the top panel and luckily there was a power icon.please fix it, it's too cool to be bugged like that. [Bug]: 

### ISSUE THREAD

**Issue by Newlumedina** [SamSprung/SamSprung-TooUI#125]
### Issue Description

Please fix the minor system issues. People will really love this tool including me! I been waiting for this
Idk y it does this it literally stops functioning after few hours, the swipe back to previous screen ,swipe from any side of the screen,also swipe up from bottom middle screen to return to homescreen just stops
To turn off my phone I had to pull down the top panel and luckily there was a power icon.please fix it, it's too cool to be bugged like that. 

### Logcat Output

```shell
Please fix the minor system issues. People will really love this tool including me! I been waiting for this
Idk y it does this it literally stops functioning after few hours, the swipe back to previous screen ,swipe from any side of the screen,also swipe up from bottom middle screen to return to homescreen just stops
To turn off my phone I had to pull down the top panel and luckily there was a power icon.please fix it, it's too cool to be bugged like that.
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
If we're calling it a bug, then replacing the log section with a copy of the description makes it hard to find it. It likely isn't a bug, though, since your phone eventually kills off the service and there are instructions to prevent it.

https://github.com/SamSprung/SamSprung-TooUI/wiki#prevent-service-termination
