### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MMS2022** [SamSprung/SamSprung-TooUI#167]
### Issue Description

Have installed and have owed all directions still does not appear iny widgets.

### Logcat Output

```shell
Still does not appear to add on my cover screen
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
This app is not a widget. See https://github.com/SamSprung/SamSprung-TooUI/wiki
