### ISSUE TITLE
[Bug]: samsprung app

### ISSUE THREAD

**Issue by Adpeter56** [SamSprung/SamSprung-TooUI#173]
### Issue Description

Download complete no front images

### Logcat Output

```shell
Paste
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
Have you followed the setup instructions?

**Comment by Adpeter56** [comment]
I have it get it up and running i need to press on the littel men in the corner when the the fhone is close
