### ISSUE TITLE
[Bug]: search bar 

### ISSUE THREAD

**Issue by Maxhc70** [SamSprung/SamSprung-TooUI#196]
### Issue Description

Search bar is not on for all the apps, it disappear so you cant go back or exit the app. How to solve please? 

### Logcat Output

```shell
Search bar is not on for all the apps, it disappear so you cant go back or exit the app. How to solve please?
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
The only search bar that's part of the launcher is the one in the app drawer. Pressing the X will clear it and close the search.
