### ISSUE TITLE
[Bug]: navigation bar not working well

### ISSUE THREAD

**Issue by Maxhc70** [SamSprung/SamSprung-TooUI#198]
### Issue Description

When i open an app the navigation bar does not appear so i remain Blocked in the app. And to solve the issue i need to open the mobile.
This happen always so app is really beautiful but if i always need to open the mobile.... It is sad.

Also all the settings changes themselves alone they do not maintain my choices. 

### Logcat Output

```shell
When i open an app the navigation bar does not appear so i remain Blocked in the app. And to solve the issue i need to open the mobile.
This happen always so app is really beautiful but if i always need to open the mobile.... It is sad.

Also all the settings changes themselves alone they do not maintain my choices.
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment]
Not one of the issues has included a log, so there is no way to tell why you're having so many issues.
