### ISSUE TITLE
[Bug]: SamSprung Main Page on Full screen is not readable

### ISSUE THREAD

**Issue by adepaoli** [SamSprung/SamSprung-TooUI#199]
### Issue Description

The fonts and the text are too small and the background is "transparently blurred" making the readability very low.

Device: Galaxy Flip 3 5G

![photo_2022-07-26_17-03-51](https://user-images.githubusercontent.com/1434299/181041643-c47763e2-d435-4091-b7f5-3964aa91d707.jpg)

### Logcat Output

```shell
N/A
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment]
It appears you have light theme set with a dark background. The slight transparency is actually a filter meant to offset that, but it appears it is not strong enough for how dark of a background is present.

**Comment by AbandonedCart** [comment]
I'll run some additional tests using more drastic wallpaper contrast and try to find a better balance between remaining visible and not washing out the background. The worst case scenario being that the background in preferences will have a separate option to disable it (since it serves no critical functional purpose).

**Comment by AbandonedCart** [comment]
28e9dff should make the text visible. There is likely no perfect scenario for everyone, so an option to disable the custom background will also be implemented in a future release.

**Comment by adepaoli** [comment]
I would suggest making the "Main Settings Page" simpler and complying with Material Design: white background, Roboto font normal size, etc. This would make the app more stylish and nice to view.

**Comment by AbandonedCart** [comment]
Thanks for the suggestion.

**Comment by AbandonedCart** [comment]
The font sizes throughout the settings page have been slightly increased when smaller fonts were used and some of the scaling has been disabled when possible. The result will be dependant on your own text and screen settings, meaning individual results may vary. Unfortunately, the device appears designed with a younger crowd in mind, so much of the UI is slimmer than what you would find on an S or Note series device.
