### ISSUE TITLE
[Bug]: Donation Page

### ISSUE THREAD

**Issue by adepaoli** [SamSprung/SamSprung-TooUI#200]
### Issue Description

I've donated but I have no feedback about it
If I try to donate the same amount I expect that Googe says I have done it already.

### Logcat Output

```shell
N/A
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment]
You should see a notice upon completion of the donation, but only one-time purchases would prevent selecting the same item again. Often times, individual donations are made for the same amount over the lifespan of the app without committing to a subscription.
