### ISSUE TITLE
Intrusive permissions

### ISSUE THREAD

**Issue by adiahickman** [SamSprung/SamSprung-TooUI#208]
### Issue Description

Every time I launch it asks if i want to allow samsprung to download unknown apps, perfect in every other way so far ❤ 

### Logcat Output

```shell
Every time I launch it asks if i want to allow samsprung to download unknown apps, perfect in every other way so far ❤
```

### Wiki Confirmation

- [X] I have read the wiki and included a valid log

**Comment by AbandonedCart** [comment]
Google Play versions update through Google Play. GitHub versions update through GitHub. GitHub isn't Google Play, so it requires permission. Considering the ideal scenario is that updates are actually being performed and it asks when the updates are checked, the best that can really be done is to only ask every time the app is out of date. That will leave the responsibility for remaining updated on you to avoid being prompted for permission to install it.
