### ISSUE TITLE
Samsprung screen gets stuck in a rotated mode

### ISSUE THREAD

**Issue by Cpt-Falcon** [SamSprung/SamSprung-TooUI#210]
I'm running into a problem where the UI overlay keeps rotating on the front screen and gets stuck in a rotated state so everything is vertical. All the applications become unusable and unclickable. Touch controls don't work until I restart Sam sprung.

I believe what causes it is when some apps decide to rotate and then I try to go back to the main screen. Speaking of which there should be some way to prevent or control when an app rotates or not. 

Thanks for your time.

**Comment by AbandonedCart** [comment]
Slide up the bottom bar in the app screen. If the right icon (the box with the arrows around it) does not have a lock, that is automatic rotation. If it does have a lock, you have locked the cover screen in portrait mode.

A lot of people tend to lock themselves in portrait mode and then make nearly identical bug reports, including the request for an option to do what they unknowingly did already.

**Comment by AbandonedCart** [comment]
A note has been added to the instructions page. It seems this button was not mentioned in the first section for the bottom bar. Tooltip dialogs will also be investigated to help better explain the button and avoid confusion.

**Comment by Cpt-Falcon** [comment]
@AbandonedCart Thank you very much I did not realize i had accidentally triggered that. That will certainly help a lot. The note on the instruction page is also a great idea.
 The only other thing is that some apps force you to go into vertical mode. If you have rotate disabled (portrait mode on), then when you switch back it remains locked in the vertical mode, at which point it becomes impossible to actually turn portrait mode off and go back to auto rotate. You can no longer bring up that bottom menu to toggle the portrait mode. At that point I force stop the app and restart it, which restores the app to its original state. In that vertical state all apps also become unresponsive. If it would be helpful I could upload a video of the behavior.

Last thing--I'm wondering, in portrait mode, should the app itself be forced to stay in the horizontal orientation? I would have guessed that enabling portrait mode meant apps were unable switch to the vertical orientation. Is there some way to force all apps to remain in the horizontal orientation, or maybe the orientation itself could automatically change based on the angle of the phone? Like if I rotate the phone by 90 degrees, switch the app to vertical mode, and vice versa. Not sure how feasible that is.

**Comment by Cpt-Falcon** [comment]
By the way, this is a wonderful application. I love this for my flip 4. I bought the keyboard too which has been excellent.

**Comment by AbandonedCart** [comment]
I'll have to double check the portrait lock. It's done using a temporary view locked in portrait to avoid messing with system settings and the internal screen. It's a bit of a cheap trick because the way the phone identifies which screen is active looks like it's trying to write a message in binary. 001010111.
