### ISSUE TITLE
[Issue]:  Not working for One UI 5 (ANDROID 13)

### ISSUE THREAD

**Issue by PLT42** [SamSprung/SamSprung-TooUI#222]
### Issue Description

Hello, my Samsung Galaxy Z Flip 4 was updated today and I received Android 13 and unfortunately your wonderful application which is very well developed I will not hide it from you. I quote that the problem is that if I activate your wonderful application I can no longer use my external screen for anything else just to launch the applications through Samsprung, I would like to know if you are aware of this problem.

### Logcat Output

```shell
Hello, my Samsung Galaxy Z Flip 4 was updated today and I received Android 13 and unfortunately your wonderful application which is very well developed I will not hide it from you. I quote that the problem is that if I activate your wonderful application I can no longer use my external screen for anything else just to launch the applications through Samsprung, I would like to know if you are aware of this problem.
```

### Guide Confirmation

- [X] I have reviewed the guide and included valid logcat content

**Comment by AbandonedCart** [comment]
Unfortunately, I cannot prepare for the proprietary changes in One UI updates ahead of when it arrives and can only fix errors I have not experienced with a log. Since I do not have the update and your issue does not include a log, we will have to wait for now.

**Comment by AbandonedCart** [comment]
Some changes have been made to address a bug in Android 13, but it has not been confirmed if this caused the issues some are experiencing or not.

**Comment by AbandonedCart** [comment]
After pouring hours and hours into trying to identify and resolve the error, it seems to be something with Android.

For now, the minimize button in the drawer will close out TooUI completely until the screen is turned off and back on. As it stands, that is the only real solution. Unfortunately, the issue is with touch detection not being handled properly.

**Comment by AbandonedCart** [comment]
Allegedly, this is the intended functionality after Android 12, but can be disabled using `adb shell settings put global block_untrusted_touches 0`
