### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by Gege1982** [SamSprung/SamSprung-TooUI#223]
### Issue Description

Dopo l'ultimo aggiornamento questa applicazione non funziona più bene. Galaxy z flip 3 5g. Aggiornamento android 13.
Prima dell'ultimo aggiornamento funzionava bene.

### Logcat Output

```shell
SamSprung (github) #b41c357
Android TIRAMISU (13)

--------- beginning of main
12-11 20:03:10.082 20520 20634 W Parcel  : Expecting binder but got null!
```

### Guide Confirmation

- [X] I have reviewed the guide and included valid logcat content

**Comment by AbandonedCart** [comment]
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/222
