### ISSUE TITLE
Problema display esterno dopo ultimo aggiornamento 

### ISSUE THREAD

**Issue by Gege1982** [SamSprung/SamSprung-TooUI#224]
Ho problemi con il display esterno. Invece di vederlo orizzontalmente si vede verticalmente. Le icone delle applicazioni quindi le vedo di traverso per vederle bene va girato il telefono. Inoltre quando clicco sulle app non si aprono, questo sempre sul display esterno.

**Comment by AbandonedCart** [comment]
Duplicate of https://github.com/SamSprung/SamSprung-TooUI/issues/223
