### ISSUE TITLE
Samsung cover screen does not work after OneUI5 update

### ISSUE THREAD

**Issue by IAJaay** [SamSprung/SamSprung-TooUI#225]
After getting OneUI4 -> OneUI5 (Android 13) update **Samsung** cover screen does not work anymore on my Flip 3. It does not react to swipe or press so cannot do anything there. Also disabling alarms does not work there. Only thing that seems to work is answering phone calls. 

Samsprung TooUI however works normally and can open it. If I disable Samsprung tooui or uninstall it , Samsung cover screen works again normally. 

A bit offtopic but also there seems to be new version of Samsprung(63b573a) in github but for some reason Play Store does not offer to update at all. My version is older(79dd0be).

**Comment by AbandonedCart** [comment]
Moved to https://github.com/SamSprung/SamSprung-TooUI/issues/222
