### ISSUE TITLE
[Issue]: can't find the widget from the cover screen widget list

### ISSUE THREAD

**Issue by ghost** [SamSprung/SamSprung-TooUI#227]
### Issue Description

[Issue]: Hi, downloaded the widget but it doesn't appear on the cover screen widget list. Therefore I can"t add it to my cover screen. 😓Could you please help? Thank you!

### Logcat Output

```shell
[Issue]: can't find the widget from the cover screen widget list
```

### Guide Confirmation

- [X] I have reviewed the guide and included valid logcat content

**Comment by AbandonedCart** [comment]
It's not a widget.
