### ISSUE TITLE
[Issue]: 'Bixby unlock required to continue' error message

### ISSUE THREAD

**Issue by jheyare** [SamSprung/SamSprung-TooUI#232]
### Issue Description

Apps won't open due to this error message

### Logcat Output

```shell
SamSprung (github) #26ec20c
OPPO TIRAMISU (13)
Secure Lock Screen

--------- beginning of main
03-11 11:16:05.677 29699 29699 E IPCThreadState: attemptIncStrongHandle(103): Not supported
03-11 11:16:05.677 29699 29699 E IPCThreadState: attemptIncStrongHandle(83): Not supported
03-11 11:16:15.446 29699 29699 E IPCThreadState: attemptIncStrongHandle(91): Not supported
03-11 11:16:18.592 29699 29699 E OplusBracketLog: [OplusViewMirrorManager] updateHostViewRootIfNeeded, not support android.view.ViewRootImpl@8296152
03-11 11:16:18.607 29699 29699 E IPCThreadState: attemptIncStrongHandle(82): Not supported
03-11 11:16:18.619 29699 29832 W Parcel  : Expecting binder but got null!
03-11 11:16:23.279 29699 29699 E IPCThreadState: attemptIncStrongHandle(97): Not supported
03-11 11:16:23.312 29699 29832 E GED     : ged_gpu_timestamp: GED_ERROR_FAIL eErr = 0, -2
```

### Guide Confirmation

- [X] I have reviewed the guide and included valid logcat content

**Comment by AbandonedCart** [comment]
Only fingerprint is supported for a secure lockscreen because there is no way to use a pin or password on the cover. Unfortunately, there are no Oppo devices on site to confirm how fingerprint is registered yet, so even that may not be available right now.

**Comment by jheyare** [comment]
Resolved by restarting my Oppo N2 flip 👍

**Comment by AbandonedCart** [comment]
Are you using fingerprint? I just removed the section that attempts the same unlock as Samsung because honestly, I have no idea how OPPO does it yet. Samsung required reverse engineering one of their widgets to find the command, so I assumed it wouldn't be the same.

**Comment by onlycatandme** [comment]
Black border on top of the application![image](https://user-images.githubusercontent.com/127506411/235571594-512255f8-9c59-4e06-ac21-615a7e5b945a.jpeg)

**Comment by AbandonedCart** [comment]
See https://samsprung.github.io/launcher/
