### ISSUE TITLE
[Issue]: Icons sometimes "duplicate" on Z Flip 3

### ISSUE THREAD

**Issue by LanCeeXD** [SamSprung/SamSprung-TooUI#235]
### Issue Description

When adding 20+ icons to the launcher and scrolling up and down the list, the icons start appearing and replacing different ones, despite setting it in alphabetical order. It's not just a visual bug and they do actually open the apps that it is replaced with. For example, I have YouTube Music at the bottom, and it gets replaced with AIMP. And that same icon will go to AIMP, effectively deleting YouTube Music. Sometimes swiping up and down, or left and right will fix it, but rarely. I don't know if the logcat caught it, so if it hasn't please help me out.
Here's a video to help demonstrate my point further: https://streamable.com/2c8lsb

### Logcat Output

```shell
SamSprung 2.5.6 (GitHub Release) #4e926d6
samsung TIRAMISU (13)
Secure Lock Screen

--------- beginning of main
09-21 16:39:48.333 31404 31741 W Parcel  : Expecting binder but got null!
09-21 16:39:49.494 31404 31741 W Parcel  : Expecting binder but got null!
09-21 16:39:49.593 31404 31404 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
09-21 16:39:49.593 31404 31404 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
09-21 16:39:49.594 31404 31404 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
09-21 16:39:49.594 31404 31404 E ThemeUtils: View class androidx.appcompat.widget.AppCompatImageView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
09-21 16:39:49.657 31404 31741 W Parcel  : Expecting binder but got null!
09-21 16:40:12.627 31404 31741 W Parcel  : Expecting binder but got null!
```

### Guide Confirmation

- [X] I have reviewed the guide and included valid logcat content

**Comment by AbandonedCart** [comment]
This is a known issue. Enable usage statistics to temporarily resolve it.

**Comment by LanCeeXD** [comment]
Where do I enable that? I can't seem to find the option

**Comment by AbandonedCart** [comment]
Launch the app from the app drawer.

**Comment by LanCeeXD** [comment]
I've done that already. I've looked in all the options and the sidebar and I can't find anything.

**Comment by AbandonedCart** [comment]
Shouldn't have to look in anything. It's the third item on the main app screen.

**Comment by LanCeeXD** [comment]
Just enabled it, the problem is actually worse now
![Screenshot_20230921_202912_SamSprung TooUI](https://github.com/SamSprung/SamSprung-TooUI/assets/18635351/1207da68-bacd-4014-9945-9d9566c4d6b8)
![Screenshot_20230921_203026_CoverScreen](https://github.com/SamSprung/SamSprung-TooUI/assets/18635351/63973542-ef2a-4097-b3ff-c55e24916f2c)

**Comment by AbandonedCart** [comment]
I don't see any duplicates. Per the description, the items are ordered by most recent launch.

**Comment by AbandonedCart** [comment]
In the newest update, you should be able to disable the usage option and return to alphabetical sorting without duplicates.
