### ISSUE TITLE
Am I the only one like this?

### ISSUE THREAD

**Issue by limoogi** [SamSprung/SamSprung-TooUI#29]
Hi 👋  After installing the latest TooUI apk for the first time, I can use Samspring on the cover screen, but after that, only Samsung Pay opens when I swipe, but no navigation bar occurs no matter what I do.thanks for reading it.

**Comment by AbandonedCart** [comment]
Swipe from the very bottom to open the menu, but aim higher to access Samsung Pay. There is no issue with them overlapping with a little practice.

**Comment by limoogi** [comment]
I got it. I have to open and close the phone repeatedly, but I have to open and close the navigation bar. It's easier, but do I have to keep opening and closing it?

**Comment by AbandonedCart** [comment]
Swiping down closes Samsung Pay

**Comment by limoogi** [comment]
Thx I love it
