### ISSUE TITLE
Keyboard doesn't work if isn't set as default

### ISSUE THREAD

**Issue by adidos87** [SamSprung/SamSprung-TooUI#80]
![Screenshot_20220212-212004_Settings](https://user-images.githubusercontent.com/45850022/153727059-1590209b-dc8a-412d-b803-8e31ea3c97f3.jpg)

When try to write into search bar ,  keyboard doesn't is show. Zflip3 android 12

**Comment by adidos87** [comment]
> That's why the instructions say do NOT set it as default. Now you know why...
Infact, if isnt set as default it doesn't works. How can i to do ?

**Comment by AbandonedCart** [comment]
For starters, the keyboard is now a separate app. Despite that, every version of it will handle it's own setting of default when needed. The best thing to do is read the directions and follow them.

**Comment by adidos87** [comment]
However now, after i've update the app, another dedicated app for keyboard was installed.  Now it work whe is Not set as default, but after I've used on the small screen, samsung keyboard doesn't appear

**Comment by adidos87** [comment]
@AbandonedCart just another thing, I've done a Donation but I can't see 3dot menu to send segnalation
![Screenshot_20220212-214731_SamSprung TooUI](https://user-images.githubusercontent.com/45850022/153727882-47424ead-26f9-43cd-96f9-d57c385239d6.jpg)
 Where I can find the menu ? My Google account is Alessandrodidomenico87@gmail.com.  thanks

**Comment by AbandonedCart** [comment]
It's the "Logcat" item. The 3 dot menu stuff is now that top bar.
