### ISSUE TITLE
Keyboard app can't update

### ISSUE THREAD

**Issue by adidos87** [SamSprung/SamSprung-TooUI#83]
I click on the notification to update,  the app is closed but when is opened another time the update isn't applied.
![Screenshot_20220214-000427_SamSprung Keyboard](https://user-images.githubusercontent.com/45850022/153779236-7d8a660b-16a5-4ab8-ba4c-139c69f36777.jpg)

**Comment by adidos87** [comment]
[samsprung_logcat (5).txt](https://github.com/SamSprung/SamSprung-TooUI/files/8056882/samsprung_logcat.5.txt)

**Comment by Adamogreco** [comment]
Good apk

**Comment by AbandonedCart** [comment]
May have to manually update to get the changes, but it's fixed.
