### ISSUE TITLE
App not appear on the cover screen anymore

### ISSUE THREAD

**Issue by adidos87** [SamSprung/SamSprung-TooUI#84]
The app doesn't appear, I've noticed the it haven't permission on top anymore.
![Screenshot_20220215-101223_SamSprung TooUI](https://user-images.githubusercontent.com/45850022/154030002-e9059d0e-714d-454d-a3df-2edc6de9b2b6.jpg)
[samsprung_logcat (6).txt](https://github.com/SamSprung/SamSprung-TooUI/files/8067546/samsprung_logcat.6.txt)

**Comment by AbandonedCart** [comment]
The should be a green bar at the bottom that slides up.

**Comment by adidos87** [comment]
> The should be a green bar at the bottom that slides up.

There isn't anymore, from yesterday

**Comment by adidos87** [comment]
https://user-images.githubusercontent.com/45850022/154064016-d3abbb30-2b67-4ebb-91a3-a12655adf160.mp4

This is video to explain

**Comment by AbandonedCart** [comment]
The video doesn't play, but try the new update. The log says you may have somehow corrupted the widget database, so the next version forces an update of it.

**Comment by adidos87** [comment]
To risolve I've remove e reinstall app

**Comment by Adamogreco** [comment]
Ya I seen it thank you
