### ISSUE TITLE
I cant acces it

### ISSUE THREAD

**Issue by deeyawnie** [SamSprung/SamSprung-TooUI#86]
The instruxtions are way to confusuing, idk if if ive done everything i nee to do in order for it to work since nothing is showing up, the widget isnt showing up. Someone pls help me.

**Comment by AbandonedCart** [comment]
What was confusing about them? Is it because you aren't seeing a widget? This isn't a widget. It's a pull up bar. The widget died with Android 11.

**Comment by AbandonedCart** [comment]
![openingdrawer](https://user-images.githubusercontent.com/1173913/154262032-193df30d-2166-4385-a718-ae52ee561ec5.png)
