### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Tiberius-Rex** [SamSprung/SamSprung-TooUI#93]
### Issue Description

None of my apps open on the cover screen, they all open on the phone, and the cover screen returns to normal. Sometimes YouTube opens a window on the coverscreen, but I can't move it or press play.

### Logcat Output

```shell
What?
```

### Wiki Confirmation

- [X] I have read and understood the current wiki

**Comment by AbandonedCart** [comment]
We don't accept issues without a log. Check the wiki.
