### ISSUE TITLE
Info fingerprint unavailable 

### ISSUE THREAD

**Issue by adidos87** [SamSprung/SamSprung-TooUI#98]
When I try to open an app from external display when phone is locked, I receive following message: "fingerprint auth unavailable "
![Uploading 20220307_112759.jpg…]()
My settings are following:
![Screenshot_20220305-201103_Settings](https://user-images.githubusercontent.com/45850022/157014762-0d37a050-a035-41a9-a84b-36a397c70bbb.jpg)
![Screenshot_20220305-201050_Settings](https://user-images.githubusercontent.com/45850022/157014768-33adaae9-c346-47c3-96f9-0e834b5cdc91.jpg)

**Comment by AbandonedCart** [comment]
Italian firmware currently isn't working with direct unlock, but the current version prompts to use Bixby. Both the form and the update were avoided to post this issue with duplicate screenshots from the last one, so it was closed.

**Comment by AbandonedCart** [comment]
Needs permission.

**Comment by Adamogreco** [comment]
Got real losers around me

**Comment by AbandonedCart** [comment]
@Adamogreco Sounds like the solution is to go elsewhere. Later
